services:
  # MYSQL
  db:
    image: mysql:8.4
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=verysecurepassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - db:db

  # APACHE avec PHP
  apache:
    image: php:8.3-apache  # Image officielle PHP + Apache
    container_name: apache_php
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
      
    depends_on:
      - db
    working_dir: /var/www/html   
    links:
      - db:database